import 'package:flutter/material.dart';

const appBarElevation = 0.0;
const smallElevation = 5.0;
const appBarHeight = 56.0;
const badgeMargin = 2.0;
const shadowOffset = Offset(0, 4);
const bigIconSize = 36.0;
const buttonBorderRadius = 30.0;
const buttonHeight = 56.0;
const cardHeight = 160.0;
const emojiSize = 30.0;
const mainBorderRadius = 10.0;
const mainHorMargin = 25.0;
const mainVerMargin = 12.0;
const midPadding = 20.0;
const smallPadding = 10.0;
const tinyOpacity = 0.1;
const smallOpacity = 0.25;
const midOpacity = 0.5;
const overlayBorderRadius = 30.0;
const smallIconSize = 24.0;
