import 'package:flutter/material.dart';

const appBarElevation = 0.0;
const appBarHeight = 56.0;
const badgeMargin = 2.0;
const badgeOffset = Offset(0, 4);
const bigIconSize = 36.0;
const bottomOverlayHeight = 250.0;
const buttonBorderRadius = 30.0;
const buttonHeight = 56.0;
const cardHeight = 160.0;
const emojiSize = 30.0;
const mainBorderRadius = 10.0;
const mainHorMargin = 25.0;
const mainVerMargin = 12.0;
const midPadding = 20.0;
const smallPadding = 10.0;
const opacity = 0.25;
const overlayBorderRadius = 30.0;
const smallIconSize = 24.0;
