name: rest_client
description: RestAPI Client
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dio: ^4.0.0

  freezed_annotation: ^2.1.0
  json_annotation: ^4.5.0
  retrofit: ^3.0.1
  quick_quotes_quill: ^3.0.0

dev_dependencies:
  lints: ^2.0.0

  build_runner: ^2.1.11
  freezed: ^2.1.0+1
  json_serializable: ^6.1.0
  retrofit_generator: ^4.0.0
  test: ^1.16.0
