name: local_db
description: Local database package.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # local
  common:
    path: ../common

  # third party
  path: ^1.8.0
  path_provider: ^2.0.11
  sembast: ^3.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
